---
title: "Calculation"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
require(magrittr)

#install.packages("sn")
require(sn)
# ?sn::rsn
```

```{r}
#set parameters
slant <- c(0,2,10,100)
loc <- 0
sc <- 1

r <- 5000
N <- c(5, 10, 20, 40)
```

```{r}
generate_qq <- function(slant, N, location = loc, scale = sc, R = r) {
  # Quantities to calculate/generate
  delta <- slant / (sqrt(1 + slant ^ 2))
  pop_mean <- location + scale * delta * sqrt(2 / pi)
  pop_sd <- sqrt(scale ^ 2 * (1 - (2 * delta ^ 2) / pi))
  
  Z <- rnorm(R)
  sample_dist_clt <- Z / sqrt(N) * pop_sd + pop_mean
  
  sample_sn <-
  array(rsn(
  R * N,
  xi = location,
  omega = scale,
  alpha = slant
  ), dim = c(R, N))
  sample_dist_sim <- apply(sample_sn, 1, mean)
  
  # QQ plot
  qqplot(sample_dist_sim, sample_dist_clt, asp = 1, axes = FALSE, frame.plot=TRUE, ann = FALSE)
  abline(0, 1)
}
```




```{r}
x <- seq(from = -3, to = 3, by = 0.05) 

par(mfrow = c(4,5), mai=c(0.1,0.1,0.1,0.1), oma = c(0, 4, 4, 0))

for(s in slant){
  plot(dsn(x, omega = sc, xi = loc, alpha = s), type = "l", axes = FALSE, frame.plot=TRUE)
  for(n in N){
    generate_qq(slant = s, N = n)
  }
}
mtext('slant = 100        slant = 10        slant = 2        slant = 0'
      , side = 2, outer = TRUE)
mtext('Distribution            N = 5                   N = 10                  N = 20                   N = 40'
      , side = 3, outer = TRUE)
dev.copy(png, "plot.png", , width=500, height=350)
dev.off()
```


# Megan's codes down here
```{r}
# Parameters that do not change
R <- 5000
location <- 0
scale <- 1

# Parameters that will change
N <- 5
slant <- 10

# Quantites to calculate/generate
# use formula from wikipedia of skewed normal distribution
delta <- (slant/sqrt(1+slant^2))
pop_mean <- location+scale*delta*(sqrt(2/pi))
pop_sd <-sqrt(scale^2*(1-((2*delta^2)/pi)))


'
Check if we are correct
sample <- rsn(1000, xi = location, omega = scale, alpha = slant)

mean(sample)
pop_mean
sd(sample)
pop_sd
'

Z <- rnorm(R)
sample_dist_clt <- Z*(pop_sd/sqrt(N))+pop_mean

random.skew <- array(rsn(R*N, xi = location, omega = scale, alpha = slant), dim = c(R,N))
sample_dist_sim <- apply(random.skew, 1, mean)
  
# QQ plots
qqplot(sample_dist_sim, sample_dist_clt, asp = 1)
abline(0,1)

# Optional (Display the 95% CI from the clt and the sim)
```

